# Atividade Prática 11 - Lidando com Dados do Mundo Real

Este _notebook_ é responsável por acessar as páginas web da kworb e salvar as informações das 200 músicas mais populares globalmente deste ano `.csv`.

Para isso se baixa as informações dos HTMLs utilizando Pandas.

In [1]:
import pandas as pd

df = pd.read_html('https://kworb.net/ww/archive/20260820.html') # Pelo HTML se tratar de dados tabulares se torna mais 
                                                                # simples a extração.
df = df[0] # ww significa world wide (mundialmente)

In [2]:
df.head()

,Pos,P+,Artist and Title,Days,Pk,(x?),Pts,Pts+,TPts,US,...,LT,NG,PE,PT,RO,SA,SI,SK,UA,VN
0,1,+1,BIGBANG - BiiiG,2,1,(x1),16190,967,0.031,13.0,...,NaN,NaN,1.0,NaN,83.0,1.0,NaN,48.0,89.0,1.0
1,2,-1,Shakira & Burna Boy - Dai Dai,98,1,(x40),15474,-351,1.497,16.0,...,NaN,NaN,NaN,NaN,9.0,4.0,2.0,1.0,NaN,NaN
2,3,=,"HUGEL, Imael Angel & Ultra Naté - Movin' To Th...",91,1,(x2),15000,35,1.130,52.0,...,79.0,NaN,110.0,NaN,5.0,NaN,NaN,2.0,NaN,NaN
3,4,+1,Ella Langley - Choosin' Texas,308,4,NaN,9548,-85,1.789,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,-1,Kimo Sounds - Rise Slow,80,3,(x8),9044,-1078,0.583,99.0,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,50.0,99.0,NaN

In [3]:

df.info() #

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 69 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Pos               200 non-null    int64
 1   P+                200 non-null    str
 2   Artist and Title  200 non-null    str
 3   Days              200 non-null    int64
 4   Pk                200 non-null    int64
 5   (x?)              47 non-null     str
 6   Pts               200 non-null    int64
 7   Pts+              200 non-null    int64
 8   TPts              200 non-null    float64
 9   US                97 non-null     float64
 10  UK                95 non-null     float64
 11  DE                84 non-null     float64
 12  AU                91 non-null     float64
 13  JP                31 non-null     float64
 14  AT                47 non-null     float64
 15  BE                43 non-null     float64
 16  CA                94 non-null     float64
 17  CH                54 non-null     float64
 18  ES                35 non-null     float64
 19  FR                52 non-null     float64
 20  ID                28 non-null     float64
 21  IN                18 non-null     float64
 22  IT                32 non-null     float64
 23  MX                32 non-null     float64
 24  NL                58 non-null     float64
 25  RU                16 non-null     float64
 26  TH                29 non-null     float64
 27  TR                14 non-null     float64
 28  ZA                24 non-null     float64
 29  AE                11 non-null     float64
 30  BR                23 non-null     float64
 31  CO                15 non-null     float64
 32  DK                27 non-null     float64
 33  HK                13 non-null     float64
 34  IE                19 non-null     float64
 35  LU                13 non-null     float64
 36  MY                25 non-null     float64
 37  NO                25 non-null     float64
 38  NZ                31 non-null     float64
 39  PH                14 non-null     float64
 40  PL                22 non-null     float64
 41  SE                23 non-null     float64
 42  SG                15 non-null     float64
 43  TW                16 non-null     float64
 44  AR                13 non-null     float64
 45  CL                18 non-null     float64
 46  CR                2 non-null      float64
 47  CZ                14 non-null     float64
 48  EC                5 non-null      float64
 49  EE                4 non-null      float64
 50  EG                14 non-null     float64
 51  FI                3 non-null      float64
 52  GR                6 non-null      float64
 53  GT                4 non-null      float64
 54  HU                5 non-null      float64
 55  IL                3 non-null      float64
 56  KE                0 non-null      float64
 57  KZ                9 non-null      float64
 58  LB                3 non-null      float64
 59  LT                6 non-null      float64
 60  NG                3 non-null      float64
 61  PE                15 non-null     float64
 62  PT                7 non-null      float64
 63  RO                19 non-null     float64
 64  SA                4 non-null      float64
 65  SI                5 non-null      float64
 66  SK                17 non-null     float64
 67  UA                9 non-null      float64
 68  VN                15 non-null     float64
dtypes: float64(61), int64(5), str(3)
memory usage: 107.9 KB

In [4]:
ww_df = df[['Artist and Title', 'Pts', 'Pts+', 'TPts']] # Informações que serão utilizadas.
ww_df.head()

                                    Artist and Title    Pts  Pts+   TPts
0                                    BIGBANG - BiiiG  16190   967  0.031
1                      Shakira & Burna Boy - Dai Dai  15474  -351  1.497
2  HUGEL, Imael Angel & Ultra Naté - Movin' To Th...  15000    35  1.130
3                      Ella Langley - Choosin' Texas   9548   -85  1.789
4                            Kimo Sounds - Rise Slow   9044 -1078  0.583

Será criado um DataFrame com o Nome do Artista (_artista_), Nome da Música (_musica_), média de pontos (_pts_mean_), média de pontos ganhos(_pts_gan_mean_), média do total de pontos(_pts_tot_mean_),

Primeiro foram reunidas as informações diárias dos ranques.

In [5]:
# Teste da função utilizada para todos os demais htmls
def extrair_artistas(artistas_e_musica):
    try :
        
        artistas, musica = artistas_e_musica.strip().rsplit(' - ', 1)# Utiliza o `rsplit` que lê a linha da direita 
                                                    # para a esquerda com no máximo uma ocorrência, como o nome da 
                                                    # música vem antes nessa ordem, logo é separado
    
        artistas = artistas.strip().split(', ') # Artistas são separados por `,` ou por `&` 
                                                    
        artistas = [a for a_s in artistas for a in a_s.strip().rsplit(' & ', 1)] # Basicamente um `flat map`
                                                                                # Pois ao serparar por `,` depois se deve
                                                                                # separar por `&` utiliando `a_s`, caso
                                                                                # não haja será  finaliza, se for percorre 
                                                                                # a nova lista `a`, retornando uma lista.
                                                                                # Também lido da direita para a esquerda.
        
        return artistas, musica # Retorna os artistas da música e a música em uma tupla

    except Exception as e:
        print(artistas_e_musica)
    raise e

def extrair_info(linha):
    
    artistas, musica = extrair_artistas(linha['Artist and Title']) 
    musicas = [] # Extraída os artistas da música demais informações são distribuídas por referenciar ao mesmo artista.
    for artista in artistas:
        musicas.append([artista, musica, linha['Pts'], linha['Pts+'], linha['TPts']])

    return musicas

def montar_dataframe(dataframe):
    infos_lista = dataframe.apply(extrair_info, axis=1) # Para percorrer por linha e não coluna usa-se `axis`=1
    
    infos = [info for infos in infos_lista for info in infos] # Novamente list comprehension para pegar a lista de listas
                                                                # e planar elas (`flat`)
    
    tabela_musica = pd.DataFrame(data=infos, columns=['artista', 'musica', 'pontos', 'pts_ganho', 'pts_calc'])
                                                    # Colunas definas, utilizadas para os cálculos posteriores
    
    return tabela_musica

montar_dataframe(ww_df)

                      artista             musica  pontos  pts_ganho  pts_calc
0                     BIGBANG              BiiiG   16190        967     0.031
1                     Shakira            Dai Dai   15474       -351     1.497
2                   Burna Boy            Dai Dai   15474       -351     1.497
3                       HUGEL  Movin' To The Sun   15000         35     1.130
4                 Imael Angel  Movin' To The Sun   15000         35     1.130
..                        ...                ...     ...        ...       ...
245                    Eminem      Lose Yourself    1044         94     3.860
246       Usagi(CV:Ozawa Ari)          Usagi Rap    1041        114     0.031
247   Momonga(CV:Iguchi Yuka)          Usagi Rap    1041        114     0.031
248     Mermaid(CV:Oki Saeko)          Usagi Rap    1041        114     0.031
249  Mermaid(CV:Nanase Ayaka)          Usagi Rap    1041        114     0.031

[250 rows x 5 columns]

In [6]:
import datetime as dt
import time

def data_to_str(data):
    '''Converte a data para o formato utilizado na URL. Ex: para a data do dia 20/08/2026 retorna "20260820"'''

    year = data.year
    
    month_str = str(data.month) 
    if data.month < 10:
        month_str = f'0{str(data.month)}' # O formato utilizado coloca 0 em numeoros sem casas decimais ou seja ao 
                                            # invés de 8 é utilizado '08'. Essa regra se aplica para meses e dias.

    day_str = str(data.day) 
    if data.day < 10:
        day_str = f'0{str(data.day)}' # Convertido conforme formato explicado.
        
    
    return f'{year}{month_str}{day_str}'
    

def extrair_tabela_dia(data):
    '''Retorna um `DataFrame` com as informações diárias das músicas'''

    str_date = data_to_str(data)

    url = f'https://kworb.net/ww/archive/{str_date}.html' # Como cada endereço do site possui apenas a data de
                                                            # diferença basta mudar a data da url

    print(f'Extraindo dados da url... \n{url}')

    time.sleep(1) # Temporizador para não enviar muitas requisições de uma vez para o site. 
    
    df_data = pd.read_html(url)[0] # Acessa o DataFrame da página semelhante ao teste no início do notebook.

    print(f'Montando `DataFrame`...')
    
    df_montado = montar_dataframe(df_data) # Monta o `DataFrame` conforme o teste.

    df_montado['data'] = str_date # Para que possa indentificar o dia dos registros das datas.

    print(f'Retornando novo `DataFrame`\n')
    
    return df_montado


# data_exemplo = dt.date.fromisoformat('2026-08-19')
data_exemplo = dt.date.fromisoformat('2026-01-10')

df_dia = extrair_tabela_dia(data_exemplo)

nome_arquivo = f'kworb_ww_{data_to_str(data_exemplo)}.csv'
df_dia.to_csv('dados/teste_'+nome_arquivo, sep=';', decimal=',', index=False) # Só vai ser escrito se todos os meses funcionarem

Extraindo dados da url...
https://kworb.net/ww/archive/20260110.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Foi percorrido as páginas desde o início do ano até o dia 20 de Agosto de 2026, a iteração é feita em intervalos de meses e cada mês é salvo para que haja um ponto de 
parada de cada mês caso haja algum erro e precise ser tratado.

In [7]:
def intervalo_data(data_inicio, data_fim):
    '''Cria um intervalo com base nas datas informadas'''
    return (dt.date.fromisoformat(data_inicio), dt.date.fromisoformat(data_fim))

janeiro = intervalo_data('2026-01-01', '2026-01-31')
fevereiro = intervalo_data('2026-02-01', '2026-02-28')
marco = intervalo_data('2026-03-01', '2026-03-31')
abril = intervalo_data('2026-04-01', '2026-04-30')
maio = intervalo_data('2026-05-01', '2026-05-31')
junho = intervalo_data('2026-06-01', '2026-06-30')
julho = intervalo_data('2026-07-01', '2026-07-31')
agosto = intervalo_data('2026-08-01', '2026-08-20')

meses = [janeiro, fevereiro, marco, abril, junho, julho, agosto] # Intervalos definidos

colunas = ['artista', 'musica', 'pontos', 'pts_ganho', 'pts_calc', 'data']

df_ano = pd.DataFrame(data=[], columns=colunas)
for mes in meses:
    data_inicio, data_fim = mes

    print(f'\nIniciado o mês com o intervalo: {data_inicio} | {data_fim}')

    df_mes = pd.DataFrame(data=[], columns=colunas)
    
    data_atual = data_inicio
    while True:
        print(f'Iniciando extração do dia {data_atual}')
        
        df_dia = extrair_tabela_dia(data_atual)

        df_mes = pd.concat([df_mes, df_dia]) # Monta o `DataFrame` do mês de acordo com cada dia

        if data_atual != data_fim: # Condição de parada do laço
            data_atual = data_atual.replace(day = data_atual.day +1) # Adiciona um dia na Data (iteração)
        else :
            break 

    nome_arquivo = f'kworb_ww_{data_to_str(data_inicio)}-{data_to_str(data_fim)}.csv'

    print(f'Salvando arquivo {nome_arquivo}...')
    df_mes.to_csv('dados/'+nome_arquivo, sep=';', decimal=',', index=False) 

    df_ano = pd.concat([df_ano, df_mes]) # Monta o `DataFrame` do ano de acordo com cada mês
    
    print('Mês finalizado')

df_ano.to_csv('dados/kworb_ww_2026.csv', sep=';', decimal=',', index=False) # Só vai ser escrito se todos os meses funcionarem

Iniciado o mês com o intervalo: 2026-01-01 | 2026-01-31
Iniciando extração do dia 2026-01-01
Extraindo dados da url...
https://kworb.net/ww/archive/20260101.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-02
Extraindo dados da url...
https://kworb.net/ww/archive/20260102.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-03
Extraindo dados da url...
https://kworb.net/ww/archive/20260103.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-04
Extraindo dados da url...
https://kworb.net/ww/archive/20260104.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-05
Extraindo dados da url...
https://kworb.net/ww/archive/20260105.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-06
Extraindo dados da url...
https://kworb.net/ww/archive/20260106.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-07
Extraindo dados da url...
https://kworb.net/ww/archive/20260107.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-08
Extraindo dados da url...
https://kworb.net/ww/archive/20260108.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-09
Extraindo dados da url...
https://kworb.net/ww/archive/20260109.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-10
Extraindo dados da url...
https://kworb.net/ww/archive/20260110.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-11
Extraindo dados da url...
https://kworb.net/ww/archive/20260111.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-12
Extraindo dados da url...
https://kworb.net/ww/archive/20260112.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-13
Extraindo dados da url...
https://kworb.net/ww/archive/20260113.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-14
Extraindo dados da url...
https://kworb.net/ww/archive/20260114.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-15
Extraindo dados da url...
https://kworb.net/ww/archive/20260115.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-16
Extraindo dados da url...
https://kworb.net/ww/archive/20260116.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-17
Extraindo dados da url...
https://kworb.net/ww/archive/20260117.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-18
Extraindo dados da url...
https://kworb.net/ww/archive/20260118.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-19
Extraindo dados da url...
https://kworb.net/ww/archive/20260119.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-20
Extraindo dados da url...
https://kworb.net/ww/archive/20260120.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-21
Extraindo dados da url...
https://kworb.net/ww/archive/20260121.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-22
Extraindo dados da url...
https://kworb.net/ww/archive/20260122.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-23
Extraindo dados da url...
https://kworb.net/ww/archive/20260123.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-24
Extraindo dados da url...
https://kworb.net/ww/archive/20260124.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-25
Extraindo dados da url...
https://kworb.net/ww/archive/20260125.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-26
Extraindo dados da url...
https://kworb.net/ww/archive/20260126.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-27
Extraindo dados da url...
https://kworb.net/ww/archive/20260127.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-28
Extraindo dados da url...
https://kworb.net/ww/archive/20260128.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-29
Extraindo dados da url...
https://kworb.net/ww/archive/20260129.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-30
Extraindo dados da url...
https://kworb.net/ww/archive/20260130.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-01-31
Extraindo dados da url...
https://kworb.net/ww/archive/20260131.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Salvando arquivo kworb_ww_20260101-20260131.csv...
Mês finalizado

Iniciado o mês com o intervalo: 2026-02-01 | 2026-02-28
Iniciando extração do dia 2026-02-01
Extraindo dados da url...
https://kworb.net/ww/archive/20260201.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-02
Extraindo dados da url...
https://kworb.net/ww/archive/20260202.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-03
Extraindo dados da url...
https://kworb.net/ww/archive/20260203.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-04
Extraindo dados da url...
https://kworb.net/ww/archive/20260204.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-05
Extraindo dados da url...
https://kworb.net/ww/archive/20260205.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-06
Extraindo dados da url...
https://kworb.net/ww/archive/20260206.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-07
Extraindo dados da url...
https://kworb.net/ww/archive/20260207.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-08
Extraindo dados da url...
https://kworb.net/ww/archive/20260208.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-09
Extraindo dados da url...
https://kworb.net/ww/archive/20260209.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-10
Extraindo dados da url...
https://kworb.net/ww/archive/20260210.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-11
Extraindo dados da url...
https://kworb.net/ww/archive/20260211.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-12
Extraindo dados da url...
https://kworb.net/ww/archive/20260212.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-13
Extraindo dados da url...
https://kworb.net/ww/archive/20260213.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-14
Extraindo dados da url...
https://kworb.net/ww/archive/20260214.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-15
Extraindo dados da url...
https://kworb.net/ww/archive/20260215.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-16
Extraindo dados da url...
https://kworb.net/ww/archive/20260216.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-17
Extraindo dados da url...
https://kworb.net/ww/archive/20260217.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-18
Extraindo dados da url...
https://kworb.net/ww/archive/20260218.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-19
Extraindo dados da url...
https://kworb.net/ww/archive/20260219.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-20
Extraindo dados da url...
https://kworb.net/ww/archive/20260220.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-21
Extraindo dados da url...
https://kworb.net/ww/archive/20260221.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-22
Extraindo dados da url...
https://kworb.net/ww/archive/20260222.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-23
Extraindo dados da url...
https://kworb.net/ww/archive/20260223.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-24
Extraindo dados da url...
https://kworb.net/ww/archive/20260224.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-25
Extraindo dados da url...
https://kworb.net/ww/archive/20260225.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-26
Extraindo dados da url...
https://kworb.net/ww/archive/20260226.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-27
Extraindo dados da url...
https://kworb.net/ww/archive/20260227.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-02-28
Extraindo dados da url...
https://kworb.net/ww/archive/20260228.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Salvando arquivo kworb_ww_20260201-20260228.csv...
Mês finalizado

Iniciado o mês com o intervalo: 2026-03-01 | 2026-03-31
Iniciando extração do dia 2026-03-01
Extraindo dados da url...
https://kworb.net/ww/archive/20260301.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-02
Extraindo dados da url...
https://kworb.net/ww/archive/20260302.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-03
Extraindo dados da url...
https://kworb.net/ww/archive/20260303.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-04
Extraindo dados da url...
https://kworb.net/ww/archive/20260304.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-05
Extraindo dados da url...
https://kworb.net/ww/archive/20260305.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-06
Extraindo dados da url...
https://kworb.net/ww/archive/20260306.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-07
Extraindo dados da url...
https://kworb.net/ww/archive/20260307.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-08
Extraindo dados da url...
https://kworb.net/ww/archive/20260308.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-09
Extraindo dados da url...
https://kworb.net/ww/archive/20260309.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-10
Extraindo dados da url...
https://kworb.net/ww/archive/20260310.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-11
Extraindo dados da url...
https://kworb.net/ww/archive/20260311.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-12
Extraindo dados da url...
https://kworb.net/ww/archive/20260312.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-13
Extraindo dados da url...
https://kworb.net/ww/archive/20260313.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-14
Extraindo dados da url...
https://kworb.net/ww/archive/20260314.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-15
Extraindo dados da url...
https://kworb.net/ww/archive/20260315.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-16
Extraindo dados da url...
https://kworb.net/ww/archive/20260316.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-17
Extraindo dados da url...
https://kworb.net/ww/archive/20260317.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-18
Extraindo dados da url...
https://kworb.net/ww/archive/20260318.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-19
Extraindo dados da url...
https://kworb.net/ww/archive/20260319.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-20
Extraindo dados da url...
https://kworb.net/ww/archive/20260320.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-21
Extraindo dados da url...
https://kworb.net/ww/archive/20260321.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-22
Extraindo dados da url...
https://kworb.net/ww/archive/20260322.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-23
Extraindo dados da url...
https://kworb.net/ww/archive/20260323.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-24
Extraindo dados da url...
https://kworb.net/ww/archive/20260324.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-25
Extraindo dados da url...
https://kworb.net/ww/archive/20260325.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-26
Extraindo dados da url...
https://kworb.net/ww/archive/20260326.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-27
Extraindo dados da url...
https://kworb.net/ww/archive/20260327.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-28
Extraindo dados da url...
https://kworb.net/ww/archive/20260328.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-29
Extraindo dados da url...
https://kworb.net/ww/archive/20260329.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-30
Extraindo dados da url...
https://kworb.net/ww/archive/20260330.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-03-31
Extraindo dados da url...
https://kworb.net/ww/archive/20260331.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Salvando arquivo kworb_ww_20260301-20260331.csv...
Mês finalizado

Iniciado o mês com o intervalo: 2026-04-01 | 2026-04-30
Iniciando extração do dia 2026-04-01
Extraindo dados da url...
https://kworb.net/ww/archive/20260401.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-02
Extraindo dados da url...
https://kworb.net/ww/archive/20260402.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-03
Extraindo dados da url...
https://kworb.net/ww/archive/20260403.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-04
Extraindo dados da url...
https://kworb.net/ww/archive/20260404.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-05
Extraindo dados da url...
https://kworb.net/ww/archive/20260405.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-06
Extraindo dados da url...
https://kworb.net/ww/archive/20260406.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-07
Extraindo dados da url...
https://kworb.net/ww/archive/20260407.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-08
Extraindo dados da url...
https://kworb.net/ww/archive/20260408.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-09
Extraindo dados da url...
https://kworb.net/ww/archive/20260409.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-10
Extraindo dados da url...
https://kworb.net/ww/archive/20260410.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-11
Extraindo dados da url...
https://kworb.net/ww/archive/20260411.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-12
Extraindo dados da url...
https://kworb.net/ww/archive/20260412.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-13
Extraindo dados da url...
https://kworb.net/ww/archive/20260413.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-14
Extraindo dados da url...
https://kworb.net/ww/archive/20260414.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-15
Extraindo dados da url...
https://kworb.net/ww/archive/20260415.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-16
Extraindo dados da url...
https://kworb.net/ww/archive/20260416.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-17
Extraindo dados da url...
https://kworb.net/ww/archive/20260417.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-18
Extraindo dados da url...
https://kworb.net/ww/archive/20260418.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-19
Extraindo dados da url...
https://kworb.net/ww/archive/20260419.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-20
Extraindo dados da url...
https://kworb.net/ww/archive/20260420.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-21
Extraindo dados da url...
https://kworb.net/ww/archive/20260421.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-22
Extraindo dados da url...
https://kworb.net/ww/archive/20260422.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-23
Extraindo dados da url...
https://kworb.net/ww/archive/20260423.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-24
Extraindo dados da url...
https://kworb.net/ww/archive/20260424.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-25
Extraindo dados da url...
https://kworb.net/ww/archive/20260425.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-26
Extraindo dados da url...
https://kworb.net/ww/archive/20260426.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-27
Extraindo dados da url...
https://kworb.net/ww/archive/20260427.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-28
Extraindo dados da url...
https://kworb.net/ww/archive/20260428.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-29
Extraindo dados da url...
https://kworb.net/ww/archive/20260429.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-04-30
Extraindo dados da url...
https://kworb.net/ww/archive/20260430.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Salvando arquivo kworb_ww_20260401-20260430.csv...
Mês finalizado

Iniciado o mês com o intervalo: 2026-06-01 | 2026-06-30
Iniciando extração do dia 2026-06-01
Extraindo dados da url...
https://kworb.net/ww/archive/20260601.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-06-02
Extraindo dados da url...
https://kworb.net/ww/archive/20260602.html
Montando `DataFrame`...
Retornando novo `DataFrame`

Iniciando extração do dia 2026-06-03

### Referências

[1] https://kworb.net/ww/ (20/08/2026).

[2] https://docs.python.org/3/library/datetime.html (20/08/2026).

[3] https://stackoverflow.com/questions/15012228/splitting-on-last-delimiter-in-python-string (20/08/2026)