# Atividade Prática 11 - Lidando com Dados do Mundo Real

Este _notebook_ é responsável por transformar os dados extraídos de `extrair_dados_musicrainz_pratica`.

Utiliando arquivo extraído vamos montar o arquivo que reuni os a música, gênero e pontuações para ser utilizado no
treinamento do modelo.

Músicas sem gênero não foram consideradas, apesar de remover os dados não ser uma boa prática o ideal seria utilizar um modelo que populasse os gêneros de acordo com outras caracterstícas, 
mas isso pode ser uma outra atividade por tanto foi utilizado apenas as músicas com genêro para realizar o teste do modelo.

In [1]:
import pandas as pd

PATH_DIRETORIO = 'dados/bkp/final_08/musicbrainz/'

PATH_ARQUIVO_MUSICAS_GENEROS = PATH_DIRETORIO + 'musicas_generos.csv'

musicas_generos_df = pd.read_csv(PATH_ARQUIVO_MUSICAS_GENEROS, sep=';', decimal=',')

musicas_generos_df = musicas_generos_df.dropna().reset_index()[['id_musica', 'generos']].set_index('id_musica')

musicas_generos_df.tail(10)

                                                                                generos
id_musica
01a02706-e028-7424-9d5e-120f8c290c70                                                pop
01a02706-e028-7424-9d5e-12100d8bb388  acoustic rock|alternative metal|alternative ro...
01a02706-e028-7424-9d5e-1211afbe16f9                                  alternative metal
01a02706-e028-7424-9d5e-12138339ca32                                  rock|thrash metal
01a02706-e028-7424-9d5e-12156f714e50                                  rock|thrash metal
01a02706-e028-7424-9d5e-121ae4de4c60                       edm|future rave|hands up|pop
01a02706-e028-7424-9d5e-1230f5c5cc59  club|dance|dancehall|downtempo|electronic|elec...
01a02706-e028-7424-9d5e-123e77a3b087                                       pop|pop rock
01a02706-e028-7424-9d5e-1246b72dec8a  folk|folk rock|indie pop|pop|pop rock|rock|sof...
01a02706-e028-7424-9d5e-1249c3c780cd                               hip hop|pop rap|trap

Os genêros são separados por `|` foram criados colunas nos `DataFrames`
para cada gênero encontrado, dessa maneira a coluna irá possuir o valor de `0` indicando que 
não pertence a aquele gênero e `1` indicando que pertence.

In [2]:
# 'id_musica' in musicas_generos_df.columns.values

with open(PATH_ARQUIVO_MUSICAS_GENEROS, 'r') as arquivo:
    first = True
    for linha in arquivo:
        if first : # Pula a primeira linha que é o cabeçalho
            first = False
            continue 
        
        id_musica, generos_str = linha.strip().split(';')

        generos = [] # Transforma os gêneros em lista para serem percorridos
        if generos_str != '':
            generos = generos_str.strip().split('|')

        #print(f'id_musica:{id_musica} , generos:{generos}')

        for genero in generos:

            if genero not in musicas_generos_df.columns.values: # Inicializa a coluna caso
                                                                # ainda não exista
                musicas_generos_df[genero] = 0

            musicas_generos_df.loc[id_musica, genero] = 1 # Atribui 1 nas colunas em que 
                                                            # a música pertence ao gênero.

# Warning por conta do tamanho do `DataFrame` pelo que entende-se na mensagem de aviso abaixo.

/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0
/var/folders/6t/7v9yyk057kz78srfh2j30m6w0000gn/T/ipykernel_76739/3317913903.py:22: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  musicas_generos_df[genero] = 0

In [3]:
musicas_generos_df.tail(3)

,generos,electro,electronic,pop,alternative metal,alternative rock,heavy metal,pop rock,post-grunge,rock,...,rap rock,celtic new age,glam metal,pop metal,gothic,gothic rock,progressive metal,rap metal,future rave,hands up
id_musica,,,,,,,,,,,,,,,,,,,,,
01a02706-e028-7424-9d5e-123e77a3b087,pop|pop rock,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e028-7424-9d5e-1246b72dec8a,folk|folk rock|indie pop|pop|pop rock|rock|sof...,0,0,1,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e028-7424-9d5e-1249c3c780cd,hip hop|pop rap|trap,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
PATH_ARQUIVO_MUSICA_GENEROS_0_1 = PATH_DIRETORIO + 'transformacao/musicas_generos_0_1.csv'

musicas_generos_df.to_csv(PATH_ARQUIVO_MUSICA_GENEROS_0_1, sep=';', decimal=',')

musicas_generos_df

,generos,electro,electronic,pop,alternative metal,alternative rock,heavy metal,pop rock,post-grunge,rock,...,rap rock,celtic new age,glam metal,pop metal,gothic,gothic rock,progressive metal,rap metal,future rave,hands up
id_musica,,,,,,,,,,,,,,,,,,,,,
01a02706-e024-7485-80f6-935a3c2770ff,electro|electronic|pop,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-935c776327ac,alternative metal|alternative rock|heavy metal...,0,0,0,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-935d5d4a5e5e,alternative metal|alternative rock|arena rock|...,0,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-935e17059cc1,alternative rock|rock,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e024-7485-80f6-935fd9c527ce,alternative metal|alternative rock|arena rock|...,0,0,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
01a02706-e028-7424-9d5e-121ae4de4c60,edm|future rave|hands up|pop,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
01a02706-e028-7424-9d5e-1230f5c5cc59,club|dance|dancehall|downtempo|electronic|elec...,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e028-7424-9d5e-123e77a3b087,pop|pop rock,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
01a02706-e028-7424-9d5e-1246b72dec8a,folk|folk rock|indie pop|pop|pop rock|rock|sof...,0,0,1,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
01a02706-e028-7424-9d5e-1249c3c780cd,hip hop|pop rap|trap,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0