# Prática

Para atividade prática foi utilizado dados públicos da corrida do grand prix de fórmula 1 de Silverstone em 2026.

Os dados utilizados foram buscadas através da API OpenF1 disponível em \[[14](https://openf1.org/docs/#introduction)].

A documentação da API para acessar as informações utilizadas na atividade estão disponíveis em \[[15](https://openf1.org/docs/#api-endpoints)].

In [12]:
# Imports
from urllib.request import urlopen # Os exemplos disponíveis em [15] para python utilizam o pacote `urllib` 
                                    # para fazer as requisições REST
import json # Utiliza o pacote json para deserializar o conteúdo da requisição 

import pandas as pd # Para montar os DataFrames

## Adiquirindo os dados

In [24]:
# Funções auxiliares 

def get_response(url_path: str):
    '''Função para evitar boiler plate de chamar a requisição e serilizar os dados.'''
    BASE_URL = 'https://api.openf1.org/v1'
    response = urlopen(BASE_URL + url_path)

    return json.loads(response.read().decode('utf-8')) # Serializa a resposta json para dado python lista de dicionários.

def df_response(url_path: str):
    '''Faz a requisição e retorna a resposta em um `DataFrame`'''
    return pd.DataFrame(get_response(url_path))

In [18]:
# Informações do Gran Prix de Silverstone de 2026.

# Filtra o GP de Silverstone pelo ano de 2026 e tipo corrida (Race). 
silverstone_2026 = get_response('/sessions?country_name=United%20Kingdom&session_name=Race&year=2026')[0] 
    # Lista com as informações do filtro encontrado, 

session_key = silverstone_2026['session_key'] # Para saber as informações da sessão eu preciso do indentificador dela.

session_key # 11326

11326

In [32]:
# Informações dos pilotos para poder filtras os dados por pilotos.

# Pilotos no GP de Silverstone
drivers_response = df_response(f'/drivers?session_key={session_key}')

# Apenas as informações que serão utilizadas, cor para mostrar no gráfico e o nome do pilot, indexado pelo número do pilot que é 
# único.
drivers = pd.DataFrame(index=drivers_response['driver_number'], data=drivers_response[['last_name', 'team_colour']])

drivers.head()

                last_name team_colour
driver_number
1              Verstappen      4781D7
3                  Hadjar      4781D7
5                   Perez      909090
6               Antonelli      00D7B6
10                  Albon      1868DB

In [35]:
# Informações das voltas do GP de Silverstone

laps_response = df_response(f'/laps?session_key={session_key}')

laps = laps_response[['driver_number', 'lap_number', 'duration_sector_1', 'duration_sector_2', 'duration_sector_3', 'lap_duration']]
laps.head()

,driver_number,lap_number,duration_sector_1,duration_sector_2,duration_sector_3,lap_duration
0,16,1,32.841,38.001,25.919,96.761
1,44,1,33.127,38.368,25.814,97.309
2,12,1,33.637,38.438,25.774,97.849
3,63,1,33.625,38.912,25.976,98.513
4,6,1,34.096,39.212,25.966,99.274

In [41]:
# Informações dos pneus utilizados no GP de Silverstone

# stints_response = df_response(f'/stints?session_key={session_key}')

stints = stints_response[['driver_number', 'compound', 'lap_start', 'lap_end', 'tyre_age_at_start']]
stints.head()

   driver_number compound  lap_start  lap_end  tyre_age_at_start
0             23   MEDIUM          1        1                  0
1             81   MEDIUM          1        2                  0
2             23     HARD          2       14                  0
3              3   MEDIUM          1       17                  0
4             27   MEDIUM          1       17                  0